databases:
  - name: meetmind-db
    plan: free
    postgresMajorVersion: 15

services:
  - type: keyvalue
    name: meetmind-redis
    plan: free
    ipAllowList: []

  - type: pserv
    name: meetmind-whisper
    plan: starter
    runtime: image
    image:
      url: docker.io/onerahmet/openai-whisper-asr-webservice:latest
    envVars:
      - key: ASR_MODEL
        value: medium
      - key: ASR_ENGINE
        value: faster-whisper

  - type: pserv
    name: meetmind-ollama
    plan: starter
    runtime: image
    image:
      url: docker.io/ollama/ollama:latest

  - type: web
    name: meetmind-backend
    plan: free
    runtime: node
    rootDir: backend
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: meetmind-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: meetmind-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: meetmind-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: meetmind-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: meetmind-db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 24h
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://meetmind-backend.onrender.com/auth/google/callback
      - key: GEMINI_API_KEY
        sync: false
      - key: LIVEKIT_URL
        value: wss://meetmind-4aiqx8o4.livekit.cloud
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: meetmind-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: meetmind-redis
          property: port
      - key: CORS_ORIGIN
        value: https://meetmind-frontend.onrender.com
      - key: FRONTEND_URL
        value: https://meetmind-frontend.onrender.com
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: WHISPER_API_URL
        value: http://meetmind-whisper:9000
      - key: OLLAMA_API_URL
        value: http://meetmind-ollama:11434
      - key: OLLAMA_MODEL
        value: qwen2:7b

  - type: web
    name: meetmind-frontend
    plan: free
    runtime: static
    rootDir: frontend
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://meetmind-backend.onrender.com
