import { getOrganizerDisplayName } from "./meetingTitleHelper";

export const exportSummaryToPdf = (
  meetingDetail: any,
  summaryElementId: string,
  lang: string = "vi"
) => {
  const summaryEl = document.getElementById(summaryElementId);
  if (!summaryEl) {
    console.error("Summary element not found");
    return;
  }

  // Backup original document title and temporarily set to meeting title for print filename
  const originalTitle = document.title;
  document.title = meetingDetail?.title || (lang === "vi" ? "Bản tóm tắt cuộc họp" : "Meeting Summary");

  // Clone the summary HTML
  const contentHtml = summaryEl.innerHTML;

  // Format meeting time
  let timeStr = "";
  if (meetingDetail?.actualStartTime || meetingDetail?.startTime) {
    const date = new Date(meetingDetail.actualStartTime || meetingDetail.startTime);
    const hours = date.getHours().toString().padStart(2, "0");
    const minutes = date.getMinutes().toString().padStart(2, "0");
    const day = date.getDate().toString().padStart(2, "0");
    const month = (date.getMonth() + 1).toString().padStart(2, "0");
    const year = date.getFullYear();
    timeStr = `${hours}:${minutes} ${day}/${month}/${year}`;
  }

  // Organizer name
  const organizerName = meetingDetail?.organizer
    ? getOrganizerDisplayName(meetingDetail.organizer.firstName, meetingDetail.organizer.lastName)
    : "";

  // Participants list
  const participantNames = (meetingDetail?.participants || [])
    .filter((p: any) => p.user && !p.isOrganizer)
    .map((p: any) => getOrganizerDisplayName(p.user.firstName, p.user.lastName))
    .filter(Boolean)
    .join(", ");

  // Labels based on language
  const labels = {
    docTitle: lang === "vi" ? "BẢN TÓM TẮT CUỘC HỌP" : "MEETING SUMMARY",
    time: lang === "vi" ? "Thời gian:" : "Time:",
    organizer: lang === "vi" ? "Người tổ chức:" : "Organizer:",
    participants: lang === "vi" ? "Người tham gia:" : "Participants:",
    brand: "MeetMind AI",
    footerText: lang === "vi" ? "Bản tóm tắt cuộc họp tự động tạo bởi MeetMind AI" : "Meeting summary auto-generated by MeetMind AI"
  };

  // Create iframe
  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  document.body.appendChild(iframe);

  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!doc) {
    document.body.removeChild(iframe);
    return;
  }

  // Write content
  doc.open();
  doc.write(`
    <html>
      <head>
        <title>${meetingDetail?.title || labels.docTitle}</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
          
          body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            color: #1e293b;
            line-height: 1.6;
            padding: 0;
            margin: 0;
            background: white;
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }
          
          /* Custom repeating Page Header and Footer */
          .page-header {
            position: fixed;
            top: 4mm;
            left: 20mm;
            right: 20mm;
            height: 10mm;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #e2e8f0;
            font-size: 9px;
            font-weight: 600;
            color: #64748b;
            background-color: white;
            z-index: 1000;
          }

          .brand-logo-small {
            font-weight: 800;
            color: #06b6d4;
            letter-spacing: 0.05em;
            text-transform: uppercase;
          }

          .header-title {
            font-weight: 700;
            color: #334155;
            max-width: 50%;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
          }

          .page-footer {
            position: fixed;
            bottom: 4mm;
            left: 20mm;
            right: 20mm;
            height: 8mm;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top: 1px solid #f1f5f9;
            font-size: 8px;
            font-weight: 500;
            color: #94a3b8;
            background-color: white;
            z-index: 1000;
          }

          /* Main layout spaces repeating on page-break */
          .page-container {
            padding: 0 20mm;
          }

          .page-header-space {
            height: 18mm;
          }

          .page-footer-space {
            height: 16mm;
          }

          .print-table {
            width: 100%;
            border-collapse: collapse;
            border: none;
            margin: 0;
          }

          .print-table td {
            border: none;
            padding: 0;
          }

          /* Header section styling inside page 1 */
          .pdf-header {
            margin-bottom: 30px;
            border-bottom: 2px solid #f1f5f9;
            padding-bottom: 20px;
          }
          
          .brand-logo {
            font-size: 11px;
            font-weight: 800;
            letter-spacing: 0.1em;
            color: #06b6d4;
            text-transform: uppercase;
            margin-bottom: 8px;
          }
          
          .pdf-title {
            font-size: 22px;
            font-weight: 800;
            color: #0f172a;
            margin: 0 0 16px 0;
            line-height: 1.2;
          }
          
          .meta-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 12px;
            background-color: #f8fafc;
            border-radius: 12px;
            padding: 14px 16px;
            font-size: 12px;
            border: 1px solid #e2e8f0;
          }
          
          .meta-item {
            display: flex;
            flex-direction: column;
            gap: 2px;
          }
          
          .meta-label {
            font-weight: 700;
            color: #64748b;
            text-transform: uppercase;
            font-size: 9px;
            letter-spacing: 0.05em;
          }
          
          .meta-value {
            font-weight: 600;
            color: #334155;
          }
          
          .meta-item-full {
            grid-column: span 2;
          }

          /* Content body styling */
          .pdf-body {
            font-size: 13px;
          }

          /* Heading styles matched to MarkdownRenderer */
          .pdf-body h1, .pdf-body h2, .pdf-body h3, .pdf-body h4 {
            font-family: 'Inter', sans-serif;
            color: #0f172a;
            font-weight: 800;
            margin-top: 24px;
            margin-bottom: 12px;
          }
          
          .pdf-body h1 { font-size: 18px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
          .pdf-body h2 { font-size: 16px; }
          .pdf-body h3 { font-size: 14px; display: flex; align-items: center; gap: 8px; }
          .pdf-body h4 { font-size: 13px; color: #475569; }

          .pdf-body p {
            margin-bottom: 12px;
            color: #334155;
          }

          /* Scoped Tables styling in summary content */
          .pdf-body table {
            width: 100%;
            border-collapse: collapse;
            margin: 16px 0;
            font-size: 11px;
          }
          
          .pdf-body th {
            background-color: #f8fafc;
            color: #475569;
            font-weight: 700;
            text-transform: uppercase;
            font-size: 9px;
            letter-spacing: 0.05em;
            border-bottom: 2px solid #e2e8f0;
          }
          
          .pdf-body th, .pdf-body td {
            padding: 8px 12px;
            text-align: left;
            border-bottom: 1px solid #e2e8f0;
          }
          
          .pdf-body tr:nth-child(even) {
            background-color: #f8fafc;
          }

          /* Checkboxes and lists */
          .pdf-body .flex {
            display: flex;
            align-items: flex-start;
            gap: 10px;
            margin-bottom: 6px;
          }

          /* Custom checkboxes */
          .pdf-body .h-4.w-4 {
            width: 14px;
            height: 14px;
            border: 1px solid #cbd5e1;
            border-radius: 4px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            margin-top: 3px;
            flex-shrink: 0;
          }

          .pdf-body .bg-cyan-500 {
            background-color: #06b6d4 !important;
            border-color: #06b6d4 !important;
            color: white !important;
          }

          .pdf-body .line-through {
            text-decoration: line-through;
            color: #94a3b8;
          }

          .pdf-body .text-cyan-500 {
            color: #06b6d4 !important;
            font-weight: 700;
          }

          /* Code styling */
          code {
            font-family: monospace;
            background-color: #f1f5f9;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 11px;
            color: #0f172a;
          }
          
          pre {
            background-color: #0f172a;
            color: #f8fafc;
            padding: 14px;
            border-radius: 8px;
            overflow-x: auto;
            margin: 16px 0;
          }
          
          pre code {
            background-color: transparent;
            padding: 0;
            color: inherit;
          }

          /* Print specific styling */
          @media print {
            body {
              margin: 0;
              padding: 0;
            }
            @page {
              margin: 0;
              size: A4;
            }
            /* Prevent orphan headings */
            h1, h2, h3, h4 {
              page-break-after: avoid;
            }
            .pdf-body table, pre, blockquote {
              page-break-inside: avoid;
            }
          }
        </style>
      </head>
      <body>
        <!-- Header & Footer repeated elements -->
        <div class="page-header">
          <span class="brand-logo-small">${labels.brand}</span>
          <span class="header-title">${meetingDetail?.title || labels.docTitle}</span>
          <span class="header-date">${timeStr}</span>
        </div>

        <div class="page-footer">
          <span>${labels.footerText}</span>
        </div>

        <div class="page-container">
          <table class="print-table">
            <thead>
              <tr>
                <td>
                  <div class="page-header-space"></div>
                </td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <!-- Summary Header (Only page 1) -->
                  <div class="pdf-header">
                    <h1 class="pdf-title">${meetingDetail?.title || labels.docTitle}</h1>
                    
                    <div class="meta-grid">
                      <div class="meta-item">
                        <span class="meta-label">${labels.time}</span>
                        <span class="meta-value">${timeStr || "---"}</span>
                      </div>
                      <div class="meta-item">
                        <span class="meta-label">${labels.organizer}</span>
                        <span class="meta-value">${organizerName || "---"}</span>
                      </div>
                      ${participantNames ? `
                      <div class="meta-item meta-item-full">
                        <span class="meta-label">${labels.participants}</span>
                        <span class="meta-value">${participantNames}</span>
                      </div>
                      ` : ''}
                    </div>
                  </div>
                  
                  <!-- Summary Body Content -->
                  <div class="pdf-body">
                    ${contentHtml}
                  </div>
                </td>
              </tr>
            </tbody>
            <tfoot>
              <tr>
                <td>
                  <div class="page-footer-space"></div>
                </td>
              </tr>
            </tfoot>
          </table>
        </div>
      </body>
    </html>
  `);
  doc.close();

  // Wait for stylesheet links / fonts to render and trigger print
  setTimeout(() => {
    iframe.contentWindow?.focus();
    iframe.contentWindow?.print();

    // Restore parent page title
    document.title = originalTitle;

    // Clean up
    setTimeout(() => {
      document.body.removeChild(iframe);
    }, 1000);
  }, 600);
};
